- name: Install dependencies
  yum:
    name: libaio
    state: latest
- name: Download binaries
  command: wget --continue -P /var/tmp http://downloads.mysql.com/archives/get/p/14/file/mysql-cluster-gpl-7.6.18-linux-glibc2.12-x86_64.tar.gz
- name: Extract binaries
  command: tar -C /usr/local -xzf /var/tmp/mysql-cluster-gpl-7.6.18-linux-glibc2.12-x86_64.tar.gz creates=/usr/local/mysql-cluster-gpl-7.6.18-linux-glibc2.12-x86_64
- name: Link binary directory to short name
  command: ln -s /usr/local/mysql-cluster-gpl-7.6.18-linux-glibc2.12-x86_64 /usr/local/mysql creates=/usr/local/mysql
- name: Create mysql group
  group: name=mysql system=yes
- name: Create myslq user
  user: name=mysql system=yes createhome=no group=mysql
- name: Create data dir
  file:  
    path: /usr/local/mysql/data
    state: directory
- name: Copy root password file
  template: src=changerootpass.txt dest=/tmp/changerootpass.txt
- name: Install mysql DB
  command: /usr/local/mysql-cluster-gpl-7.6.18-linux-glibc2.12-x86_64/bin/mysqld --initialize --user=mysql --datadir=/usr/local/mysql/data --basedir=/usr/local/mysql --init-file=/tmp/changerootpass.txt chdir=/usr/local/mysql/ creates=/usr/local/mysql/data/mysql/user.frm
- name: Set permissions
  shell: chown -R mysql /usr/local/mysql/data && chgrp -R mysql /usr/local/mysql/
- name: Install init file
  command: install /usr/local/mysql/support-files/mysql.server /etc/init.d/ creates=/etc/init.d/mysql.server
- name: Install config
  template: src=my.cnf dest=/etc/my.cnf
- name: Activate init script and start mysql server
  service: name=mysql.server enabled=yes state=started
- name: Update timestamp for mysql tables_priv to skip timestamp errors
  command: /usr/local/mysql/bin/mysql -u root -h localhost -pwelcome1 -e 'update mysql.tables_priv set Timestamp=timestamp(curdate());'
- name: Update timestamp for mysql proxies_priv to skip timestamp errors
  command: /usr/local/mysql/bin/mysql -u root -h localhost -pwelcome1 -e 'update mysql.proxies_priv set Timestamp=timestamp(curdate());'
- name: Alter tables to allow user replication
  command: /usr/local/mysql/bin/mysql -u root -h localhost -pwelcome1 -e 'ALTER TABLE mysql.{{ item }} ENGINE=NDBCLUSTER;' creates=/usr/local/mysql/data/mysql/{{ item }}.ndb
  with_items:
  - user
  - db
  - tables_priv
  - columns_priv
  - procs_priv
  - proxies_priv
