- name: Download binaries
  command: wget --continue -P /var/tmp http://downloads.mysql.com/archives/get/p/14/file/mysql-cluster-gpl-7.6.18-linux-glibc2.12-x86_64.tar.gz
- name: Extract binaries
  command: tar -C /var/tmp -xzf /var/tmp/mysql-cluster-gpl-7.6.18-linux-glibc2.12-x86_64.tar.gz creates=/var/tmp/mysql-cluster-gpl-7.6.18-linux-glibc2.12-x86_64
- name: Install nbd binaries
  command: install /var/tmp/mysql-cluster-gpl-7.6.18-linux-glibc2.12-x86_64/bin/ndbd /usr/local/bin/ndbd creates=/usr/local/bin/ndbd
- name: Install config
  template: src=my.cnf dest=/etc/my.cnf
- name: Install init file
  copy: src=ndbd.init dest=/etc/init.d/ndbd
- name: Activate init file
  service: name=ndbd enabled=yes
- name: Create mysql data dir
  file:
    path: /usr/local/mysql/data
    state: directory
- name: Initialize ndbd
  command: /usr/local/bin/ndbd --initial creates=/usr/local/mysql/data/ndbinfo/
